[package]
name = "moving_stats"
description = "Fixed size queue, which calculate moving median when you add new value(O(n))."
version = "0.1.3"
edition = "2024"
license = "MIT"
license-file = "LICENSE"
repository = "https://github.com/lamrongol/moving_stats"

[dependencies]
